# Deep learning examples using Keras + Tensorflow<a href="#Deep-learning-examples-using-Keras-+-Tensorflow" class="anchor-link">¶</a>

## Build first network using Keras<a href="#Build-first-network-using-Keras" class="anchor-link">¶</a>

In \[20\]:

    # Create simple network with Keras
    from keras.models import Sequential
    from keras.layers import Dense
    import numpy

    # load pima indians dataset
    dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
    print(dataset.shape)
    # split into input (X) and output (Y) variables
    X = dataset[:,0:8]
    Y = dataset[:,8]
    print(X.shape)
    print(Y.shape)

    (768, 9)
    (768, 8)
    (768,)

In \[21\]:

    from keras.models import Sequential
    from keras.layers import Dense

    # create first model
    model = Sequential()

    # Adding 3 dense layers
    model.add(Dense(12, input_dim=8, kernel_initializer='uniform'))
    model.add(Dense(8, kernel_initializer='uniform'))
    model.add(Dense(1, kernel_initializer='uniform'))

    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Fit the model
    model.fit(X, Y, epochs=20, batch_size=10, verbose=2)

    # Evaluate the model
    scores = model.evaluate(X, Y)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))

    Epoch 1/20
    77/77 - 1s - loss: 5.3827 - accuracy: 0.6510 - 1s/epoch - 18ms/step
    Epoch 2/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 94ms/epoch - 1ms/step
    Epoch 3/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 101ms/epoch - 1ms/step
    Epoch 4/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 82ms/epoch - 1ms/step
    Epoch 5/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 101ms/epoch - 1ms/step
    Epoch 6/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 99ms/epoch - 1ms/step
    Epoch 7/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 101ms/epoch - 1ms/step
    Epoch 8/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 101ms/epoch - 1ms/step
    Epoch 9/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 83ms/epoch - 1ms/step
    Epoch 10/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 99ms/epoch - 1ms/step
    Epoch 11/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 100ms/epoch - 1ms/step
    Epoch 12/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 100ms/epoch - 1ms/step
    Epoch 13/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 88ms/epoch - 1ms/step
    Epoch 14/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 96ms/epoch - 1ms/step
    Epoch 15/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 101ms/epoch - 1ms/step
    Epoch 16/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 82ms/epoch - 1ms/step
    Epoch 17/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 99ms/epoch - 1ms/step
    Epoch 18/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 87ms/epoch - 1ms/step
    Epoch 19/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 86ms/epoch - 1ms/step
    Epoch 20/20
    77/77 - 0s - loss: 5.3827 - accuracy: 0.6510 - 100ms/epoch - 1ms/step
    24/24 [==============================] - 0s 2ms/step - loss: 5.3827 - accuracy: 0.6510
    accuracy: 65.10%

In \[22\]:

    from keras.models import Sequential
    from keras.layers import Dense
    import numpy as np

    # Assuming you have X and Y defined
    X = np.random.rand(100, 8)
    Y = np.random.randint(2, size=(100, 1))

    # Extending the first model with activation functions
    model = Sequential()
    # specifying activation functions
    model.add(Dense(3, input_dim=8, kernel_initializer='uniform', activation='relu'))
    # model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    # Fit the model
    model.fit(X, Y, epochs=20, batch_size=10, verbose=2)
    # evaluate the model
    scores = model.evaluate(X, Y)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

    Epoch 1/20
    10/10 - 1s - loss: 0.6932 - accuracy: 0.4900 - 668ms/epoch - 67ms/step
    Epoch 2/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5200 - 17ms/epoch - 2ms/step
    Epoch 3/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5200 - 28ms/epoch - 3ms/step
    Epoch 4/20
    10/10 - 0s - loss: 0.6930 - accuracy: 0.5200 - 26ms/epoch - 3ms/step
    Epoch 5/20
    10/10 - 0s - loss: 0.6930 - accuracy: 0.5200 - 24ms/epoch - 2ms/step
    Epoch 6/20
    10/10 - 0s - loss: 0.6930 - accuracy: 0.5200 - 15ms/epoch - 1ms/step
    Epoch 7/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5200 - 22ms/epoch - 2ms/step
    Epoch 8/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5200 - 22ms/epoch - 2ms/step
    Epoch 9/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5200 - 21ms/epoch - 2ms/step
    Epoch 10/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5200 - 23ms/epoch - 2ms/step
    Epoch 11/20
    10/10 - 0s - loss: 0.6928 - accuracy: 0.5200 - 34ms/epoch - 3ms/step
    Epoch 12/20
    10/10 - 0s - loss: 0.6927 - accuracy: 0.5200 - 33ms/epoch - 3ms/step
    Epoch 13/20
    10/10 - 0s - loss: 0.6927 - accuracy: 0.5200 - 29ms/epoch - 3ms/step
    Epoch 14/20
    10/10 - 0s - loss: 0.6926 - accuracy: 0.5200 - 35ms/epoch - 3ms/step
    Epoch 15/20
    10/10 - 0s - loss: 0.6926 - accuracy: 0.5200 - 24ms/epoch - 2ms/step
    Epoch 16/20
    10/10 - 0s - loss: 0.6926 - accuracy: 0.5200 - 28ms/epoch - 3ms/step
    Epoch 17/20
    10/10 - 0s - loss: 0.6925 - accuracy: 0.5200 - 17ms/epoch - 2ms/step
    Epoch 18/20
    10/10 - 0s - loss: 0.6924 - accuracy: 0.5200 - 28ms/epoch - 3ms/step
    Epoch 19/20
    10/10 - 0s - loss: 0.6924 - accuracy: 0.5200 - 27ms/epoch - 3ms/step
    Epoch 20/20
    10/10 - 0s - loss: 0.6923 - accuracy: 0.5200 - 14ms/epoch - 1ms/step
    4/4 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.5200
    accuracy: 52.00%

In \[23\]:

    # evaluate the model
    scores = model.evaluate(X, Y)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

    4/4 [==============================] - 0s 4ms/step - loss: 0.6922 - accuracy: 0.5200
    accuracy: 52.00%

In \[24\]:

    model.summary()

    Model: "sequential_11"
    _________________________________________________________________
     Layer (type)                Output Shape              Param #   
    =================================================================
     dense_18 (Dense)            (None, 3)                 27        
                                                                     
     dense_19 (Dense)            (None, 1)                 4         
                                                                     
    =================================================================
    Total params: 31 (124.00 Byte)
    Trainable params: 31 (124.00 Byte)
    Non-trainable params: 0 (0.00 Byte)
    _________________________________________________________________

In \[25\]:

    for layer in model.layers:
        print(layer.name, layer.inbound_nodes, layer.outbound_nodes)

    dense_18 [<keras.src.engine.node.Node object at 0x0000026C36A84350>] [<keras.src.engine.node.Node object at 0x0000026C341D4F10>]
    dense_19 [<keras.src.engine.node.Node object at 0x0000026C341D4F10>] []

In \[26\]:

    model.get_weights()

Out\[26\]:

    [array([[ 0.00408516, -0.03824556,  0.05336154],
            [-0.01365287, -0.02662184, -0.0863336 ],
            [-0.00236633, -0.00805188,  0.02342406],
            [-0.0376142 ,  0.07128999,  0.02236346],
            [ 0.00530113,  0.06498241,  0.03108896],
            [ 0.00153021,  0.07855786, -0.00715087],
            [-0.04516111,  0.01733149, -0.08642501],
            [-0.01349095,  0.09663353,  0.01225374]], dtype=float32),
     array([0.        , 0.02472901, 0.03055072], dtype=float32),
     array([[-0.04207002],
            [-0.0471606 ],
            [-0.09717872]], dtype=float32),
     array([-0.02168271], dtype=float32)]

In \[27\]:

    # Multilayer Perceptron
    from keras.utils import plot_model
    # plot graph
    plot_model(model, to_file='multilayer_perceptron_graph.png')

    You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.

In \[28\]:

    # calculate predictions
    predictions = model.predict(X)
    # round predictions
    rounded = [round(x[0]) for x in predictions]
    print(predictions)
    print(rounded)

    4/4 [==============================] - 0s 4ms/step
    [[0.4929139 ]
     [0.49256784]
     [0.49132445]
     [0.49312127]
     [0.4918405 ]
     [0.4924666 ]
     [0.49152392]
     [0.49278897]
     [0.4906243 ]
     [0.49290502]
     [0.4911851 ]
     [0.49129277]
     [0.4904201 ]
     [0.49215528]
     [0.49300703]
     [0.4930487 ]
     [0.49220452]
     [0.4931847 ]
     [0.49194697]
     [0.4916489 ]
     [0.49298796]
     [0.49168053]
     [0.49209145]
     [0.49235302]
     [0.49171907]
     [0.49236298]
     [0.4921858 ]
     [0.49134725]
     [0.49295077]
     [0.4930056 ]
     [0.49296683]
     [0.49084595]
     [0.4924072 ]
     [0.49250337]
     [0.49139842]
     [0.49088252]
     [0.49323717]
     [0.49255052]
     [0.49289742]
     [0.4912865 ]
     [0.4908141 ]
     [0.49163476]
     [0.4915635 ]
     [0.49252492]
     [0.49290055]
     [0.4921511 ]
     [0.49214286]
     [0.49217358]
     [0.49220276]
     [0.49330065]
     [0.4914404 ]
     [0.49356264]
     [0.4917385 ]
     [0.49291065]
     [0.49153262]
     [0.49185982]
     [0.49325958]
     [0.49257794]
     [0.49166065]
     [0.49193636]
     [0.49134287]
     [0.49248675]
     [0.49194586]
     [0.49346983]
     [0.4924448 ]
     [0.49320865]
     [0.49258116]
     [0.48969114]
     [0.4903111 ]
     [0.49198994]
     [0.49325818]
     [0.49235588]
     [0.4910813 ]
     [0.49128672]
     [0.49293697]
     [0.49375835]
     [0.4916388 ]
     [0.49272802]
     [0.49202588]
     [0.49271235]
     [0.4937761 ]
     [0.49130383]
     [0.493002  ]
     [0.49023455]
     [0.49301904]
     [0.49375597]
     [0.49261567]
     [0.49230275]
     [0.49211094]
     [0.49104366]
     [0.49396294]
     [0.4923011 ]
     [0.4912987 ]
     [0.49163583]
     [0.49054557]
     [0.4929655 ]
     [0.49200803]
     [0.49238533]
     [0.49261132]
     [0.49303722]]
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Second Keras example<a href="#Second-Keras-example" class="anchor-link">¶</a>

In \[29\]:

    from keras.models import Sequential
    from keras.layers import Dense
    import numpy as np

    # Assuming you have X and Y defined
    X = np.random.rand(100, 8)
    Y = np.random.randint(2, size=(100, 1))

    # Extending the first model with activation functions
    model = Sequential()
    # specifying activation functions
    model.add(Dense(3, input_dim=8, kernel_initializer='uniform', activation='relu'))
    # model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    # Fit the model
    model.fit(X, Y, epochs=20, batch_size=10, verbose=2)
    # evaluate the model
    scores = model.evaluate(X, Y)
    print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

    Epoch 1/20
    10/10 - 1s - loss: 0.6932 - accuracy: 0.4700 - 626ms/epoch - 63ms/step
    Epoch 2/20
    10/10 - 0s - loss: 0.6932 - accuracy: 0.4300 - 25ms/epoch - 2ms/step
    Epoch 3/20
    10/10 - 0s - loss: 0.6932 - accuracy: 0.5300 - 21ms/epoch - 2ms/step
    Epoch 4/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5500 - 19ms/epoch - 2ms/step
    Epoch 5/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5300 - 25ms/epoch - 3ms/step
    Epoch 6/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5500 - 28ms/epoch - 3ms/step
    Epoch 7/20
    10/10 - 0s - loss: 0.6931 - accuracy: 0.5400 - 14ms/epoch - 1ms/step
    Epoch 8/20
    10/10 - 0s - loss: 0.6930 - accuracy: 0.5300 - 19ms/epoch - 2ms/step
    Epoch 9/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5400 - 15ms/epoch - 2ms/step
    Epoch 10/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5500 - 22ms/epoch - 2ms/step
    Epoch 11/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.5600 - 30ms/epoch - 3ms/step
    Epoch 12/20
    10/10 - 0s - loss: 0.6929 - accuracy: 0.6000 - 17ms/epoch - 2ms/step
    Epoch 13/20
    10/10 - 0s - loss: 0.6928 - accuracy: 0.5800 - 26ms/epoch - 3ms/step
    Epoch 14/20
    10/10 - 0s - loss: 0.6928 - accuracy: 0.5600 - 22ms/epoch - 2ms/step
    Epoch 15/20
    10/10 - 0s - loss: 0.6927 - accuracy: 0.5700 - 28ms/epoch - 3ms/step
    Epoch 16/20
    10/10 - 0s - loss: 0.6926 - accuracy: 0.5600 - 38ms/epoch - 4ms/step
    Epoch 17/20
    10/10 - 0s - loss: 0.6926 - accuracy: 0.5800 - 22ms/epoch - 2ms/step
    Epoch 18/20
    10/10 - 0s - loss: 0.6925 - accuracy: 0.6100 - 22ms/epoch - 2ms/step
    Epoch 19/20
    10/10 - 0s - loss: 0.6924 - accuracy: 0.6000 - 21ms/epoch - 2ms/step
    Epoch 20/20
    10/10 - 0s - loss: 0.6924 - accuracy: 0.5700 - 15ms/epoch - 1ms/step
    4/4 [==============================] - 0s 7ms/step - loss: 0.6923 - accuracy: 0.6200
    accuracy: 62.00%

In \[32\]:

    max_words = 1000  # For example, if you're using a vocabulary size of 1000 words

In \[33\]:

    max_words

Out\[33\]:

    1000

In \[ \]:

     

In \[ \]:

     

In \[ \]: